#!/usr/bin/env bash
# TiltyPi generation script
# Helper script that runs in a Raspbian chroot to create the TiltyPi distro
# Written by Marcus Young <myoung34@my.apsu.edu>
# Based on buildscripts from OctoPi Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
set -x
set -e

export LC_ALL=C

source /common.sh

apt-get update
apt-get install --yes raspberrypi-ui-mods lightdm || true
systemctl_if_exists enable lightdm.service || true
systemctl set-default graphical.target
