#!/usr/bin/env bash
# TiltyPi generation script
# Helper script that runs in a Raspbian chroot to create the TiltyPi distro
# Written by Marcus Young <myoung34@my.apsu.edu>
# Based on buildscripts from OctoPi Written by Guy Sheffer <guysoft at gmail dot com> and Gina Häußge <osd@foosel.net>
# GPL V3
########
set -x
set -e

export LC_ALL=C

source /common.sh

### Script ####

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
apt-get update

# in case we are building from a regular raspbian image instead of the lite one...
remove_extra=$(remove_if_installed scratch squeak-plugins-scratch squeak-vm wolfram-engine python-minecraftpi minecraft-pi sonic-pi oracle-java8-jdk bluej libreoffice-common libreoffice-core freepats greenfoot nodered)
echo "removing:" $remove_extra
apt-get remove -y --purge  $remove_extra
apt-get autoremove -y

apt-get -y --force-yes install libbluetooth-dev python3 python3-dev python3-pip git screen subversion cmake checkinstall avahi-daemon libavahi-compat-libdnssd1 libffi-dev libssl-dev curl

echo " - Reinstall iputils-ping"
apt-get install --reinstall iputils-ping

pip3 install -U tilty tilty-dashboard
mkdir -p /etc/tilty/
cat <<EOF >/etc/tilty/prod.config
[webapp]
  host=0.0.0.0
  port=5000
  database_uri="sqlite:////etc/tilty/tilt.sqlite"
EOF
cat <<EOF >/etc/tilty/prod.configspec
[webapp]
  host=string(default=127.0.0.1)
  port=string(default=5000)
  database_uri=string(default="sqlite:////etc/tilty/tilt.sqlite")
EOF
curl -sL https://raw.githubusercontent.com/myoung34/tilty-dashboard/master/config/prod_gunicorn.py >/etc/tilty/gunicorn.py

# store tiltypi commit used to build this image
echo "$TILTYPI_COMMIT" > /etc/tiltypi_commit

# Keep legacy compatibility
ln -s /etc/custompios_buildbase /etc/tiltypi_buildbase

# allow pi user to run shutdown and service commands
echo "pi ALL=NOPASSWD: /sbin/shutdown" > /etc/sudoers.d/tilty-shutdown
echo "pi ALL=NOPASSWD: /usr/sbin/service" > /etc/sudoers.d/tilty-service

#make sure users don't run git with sudo, thus breaking permissions, by adding /root/bin to the
#default sudo path and placing a git wrapper script there that checks if it's run as root
sed -i "s@secure_path=\"@secure_path=\"/root/bin:@g" /etc/sudoers
chmod +x /root/bin/git

sed -i 's@exit 0@@' /etc/rc.local
cat <<'EOT' >> /etc/rc.local
echo
echo "------------------------------------------------------------"
echo
echo "Welcome to the Tilty-Pi! "
echo " TODO: point to docs and/or webpage"
echo 
echo "------------------------------------------------------------"
echo
if [ ! -f /etc/tilty/tilty.ini ]; then
  if [ -f /boot/tilty.ini ]; then
    echo "Setting up config from /boot/tilty.ini to /etc/tilty/tilty.ini"
    mv /boot/tilty.ini /etc/tilty/tilty.ini
  fi
fi
EOT

echo 'exit 0' >> /etc/rc.local

unpack /filesystem/root /

#####################################################################
### setup services
systemctl_if_exists enable tilty.service
systemctl_if_exists enable tilty-dashboard.service
systemctl_if_exists enable tilty-watcher.service
systemctl_if_exists enable tilty-watcher.path

### Disable GUI at start
systemctl_if_exists disable lightdm.service || true

update-rc.d change_password defaults
update-rc.d change_hostname defaults

### tilt-dashboard
