name: Build Image

on:
  push:
    branches-ignore:
      - 'refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: |
        cd repository/src/image
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths

    - name: Get Latest TILTpi flow.json
      run: |
        cd repository/src/modules/tilty/filesystem/root/etc/tilty/
        curl -sL https://raw.githubusercontent.com/baronbrew/TILTpi/Aioblescan/flow.json >flow.json
    
    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x ./build_dist

    - name: Copy output
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-tiltypi-$DIST_VERSION

        cp repository/src/workspace/*.img $IMAGE.img

        echo "::set-output name=image::$IMAGE"

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.copy.outputs.image }}
        path: ${{ steps.copy.outputs.image }}.img
